language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install task -qq
before_script:
  - cp -v spec/files/taskrc $HOME/.taskrc
  - mkdir $HOME/.task
script: "bundle exec rake spec"
addons:
  apt:
    packages:
      - task
