language: ruby
rvm:
  - 1.9.2
  - 1.9.3
script: "rake spec"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install task -qq
before_script:
  - cp -v spec/files/taskrc $HOME/.taskrc
  - mkdir $HOME/.task
